### ISSUE TITLE
melty_setup.sh  ERROR  INFO

### ISSUE THREAD

**Issue by lycaste** [meltylabs/melty#43]
success Already up-to-date.
✨  Done in 0.12s.
✨  Done in 22.87s.
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated @humanwhocodes/config-array@0.11.14: Use @eslint/config-array instead
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@8.1.0: Glob versions prior to v9 are no longer supported
npm warn deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
npm warn deprecated node-tree-sitter@0.0.1: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm error code 1
npm error path /Users/yh/Documents/idea/vscode/melty/extensions/spectacular/node_modules/esbuild
npm error command failed
npm error command sh -c node install.js
npm error /Users/yh/Documents/idea/vscode/melty/extensions/spectacular/node_modules/esbuild/install.js:130
npm error     throw new Error(`Expected ${JSON.stringify("0.16.17")} but got ${JSON.stringify(stdout)}`);
npm error           ^
npm error
npm error Error: Expected "0.16.17" but got "0.23.0"
npm error     at validateBinaryVersion (/Users/yh/Documents/idea/vscode/melty/extensions/spectacular/node_modules/esbuild/install.js:130:11)
npm error     at /Users/yh/Documents/idea/vscode/melty/extensions/spectacular/node_modules/esbuild/install.js:283:5
npm error
npm error Node.js v20.17.0
npm error A complete log of this run can be found in: /Users/yh/.npm/_logs/2024-09-09T06_37_55_856Z-debug-0.log

up to date, audited 1718 packages in 5s

309 packages are looking for funding
  run `npm fund` for details

21 vulnerabilities (8 moderate, 11 high, 2 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

> melty@0.28.0 compile
> node ./esbuild.js

✘ [ERROR] Could not resolve "posthog-js"

    src/extension.ts:6:20:
      6 │ import posthog from "posthog-js";
        ╵                     ~~~~~~~~~~~~

  You can mark the path "posthog-js" as external to exclude it from the bundle, which will remove
  this error and leave the unresolved path in the bundle.

✘ [ERROR] Could not resolve "@anthropic-ai/sdk"

    src/backend/claudeAPI.ts:1:26:
      1 │ import { Anthropic } from "@anthropic-ai/sdk";
        ╵                           ~~~~~~~~~~~~~~~~~~~

  You can mark the path "@anthropic-ai/sdk" as external to exclude it from the bundle, which will
  remove this error and leave the unresolved path in the bundle.

✘ [ERROR] Could not resolve "@anthropic-ai/sdk"

    src/backend/commitMessageGenerator.ts:1:26:
      1 │ import { Anthropic } from "@anthropic-ai/sdk";
        ╵                           ~~~~~~~~~~~~~~~~~~~

  You can mark the path "@anthropic-ai/sdk" as external to exclude it from the bundle, which will
  remove this error and leave the unresolved path in the bundle.

✘ [ERROR] Could not resolve "posthog-js"

    src/HelloWorldPanel.ts:22:20:
      22 │ import posthog from "posthog-js";
         ╵                     ~~~~~~~~~~~~

  You can mark the path "posthog-js" as external to exclude it from the bundle, which will remove
  this error and leave the unresolved path in the bundle.

node:internal/streams/writable:480
      throw new ERR_INVALID_ARG_TYPE(
            ^

TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at _write (node:internal/streams/writable:480:13)
    at Writable.write (node:internal/streams/writable:508:10)
    at /Users/yh/Documents/idea/vscode/melty/extensions/spectacular/esbuild.js:119:20
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v20.17.0
npm error code ENOENT
npm error syscall open
npm error path /Users/yh/Documents/idea/vscode/melty/extensions/supermaven/package.json
npm error errno -2
npm error enoent Could not read package.json: Error: ENOENT: no such file or directory, open '/Users/yh/Documents/idea/vscode/melty/extensions/supermaven/package.json'
npm error enoent This is related to npm not being able to find a file.
npm error enoent
npm error A complete log of this run can be found in: /Users/yh/.npm/_logs/2024-09-09T06_38_16_133Z-debug-0.log

**Comment by unrealisticguy** [comment]
It seems the extensions/spectacular/package.json specifies esbuild version ^0.16.17, while extensions/package.json locks it at version 0.23.0. This version mismatch is likely causing the conflict. @jacksondc

**Comment by abhi12299** [comment]
Pull the latest code from the main branch and see the installation instructions at https://github.com/meltylabs/melty/blob/main/CONTRIBUTING.md#local-development

Also make sure to use yarn

**Comment by lycaste** [comment]
@abhi12299 
 (node -v v20.17.0 yarn -v 1.22.22)
The problem still persisted, so I changed 0.16.17 to 0.23.0, and it's working now 
However, there's a new issue. I first run:
yarn run melty:install
Then I ran ./script/code.sh, but it still gives an error: Activating extension 'meltylabs.melty' failed: Cannot find module
and some error in termianl 
RUNNING IN DEV MODE
09:17:20.675 › Checking for update
Checking for update...
09:17:20.842 › Error: Error: net::ERR_CONNECTION_REFUSED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:114482)
    at SimpleURLLoaderWrapper.emit (node:events:519:28)
Auto-updater error: Error: net::ERR_CONNECTION_REFUSED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:114482)
    at SimpleURLLoaderWrapper.emit (node:events:519:28)
(node:27619) UnhandledPromiseRejectionWarning: Error: net::ERR_CONNECTION_REFUSED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:114482)
    at SimpleURLLoaderWrapper.emit (node:events:519:28)
(Use `Electron --trace-warnings ...` to show where the warning was created)
(node:27619) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

**Comment by abhi12299** [comment]
After melty:install, you need to run melty:extension-dev to build the extension in watch mode.. and in another terminal, launch the code.sh script

**Comment by lycaste** [comment]
@abhi12299 
When I run melty:extension-dev, the following error appears. Is it because I modified the version of esbuild? 
If I use the 0.16.17 version, the first command [yarn run melty:install] fails completely. How should I fix this?

[0] 
[0] > melty@0.28.0 watch
[0] > node ./esbuild.js --watch
[0] 
[1] 
[1] > melty@0.28.0 watch:webview
[1] > cd webview-ui && npm run watch
[1] 
[0] [watch] build started
[0] ✘ [ERROR] Invalid option in build() call: "watch"
[0] 
[0]     /Users/yh/Documents/idea/vscode/melty/extensions/spectacular/node_modules/esbuild/lib/main.js:253:12:
[0]       253 │       throw new Error(`Invalid option ${where}: ${quote(key)}`);
[0]           ╵             ^
[0] 
[0]     at checkForInvalidFlags (/Users/yh/Documents/idea/vscode/melty/extensions/spectacular/node_modules/esbuild/lib/main.js:253:13)
[0]     at flagsForBuildOptions (/Users/yh/Documents/idea/vscode/melty/extensions/spectacular/node_modules/esbuild/lib/main.js:426:3)
[0]     at buildOrContextContinue (/Users/yh/Documents/idea/vscode/melty/extensions/spectacular/node_modules/esbuild/lib/main.js:913:9)
[0]     at buildOrContextImpl (/Users/yh/Documents/idea/vscode/melty/extensions/spectacular/node_modules/esbuild/lib/main.js:897:5)
[0]     at Object.buildOrContext (/Users/yh/Documents/idea/vscode/melty/extensions/spectacular/node_modules/esbuild/lib/main.js:699:5)
[0]     at /Users/yh/Documents/idea/vscode/melty/extensions/spectacular/node_modules/esbuild/lib/main.js:2024:15
[0]     at new Promise (<anonymous>)
[0]     at Object.build (/Users/yh/Documents/idea/vscode/melty/extensions/spectacular/node_modules/esbuild/lib/main.js:2023:25)
[0]     at build (/Users/yh/Documents/idea/vscode/melty/extensions/spectacular/node_modules/esbuild/lib/main.js:1874:51)
[0]     at /Users/yh/Documents/idea/vscode/melty/extensions/spectacular/esbuild.js:65:10
[0] 
[0] node:internal/streams/writable:480
[0]       throw new ERR_INVALID_ARG_TYPE(
[0]             ^
[0] 
[0] TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
[0]     at _write (node:internal/streams/writable:480:13)
[0]     at Writable.write (node:internal/streams/writable:508:10)
[0]     at /Users/yh/Documents/idea/vscode/melty/extensions/spectacular/esbuild.js:83:18
[0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
[0]   code: 'ERR_INVALID_ARG_TYPE'
[0] }
[0] 
[0] Node.js v20.17.0
[0] npm run watch exited with code 1

**Comment by abhi12299** [comment]
Yes, it seems like the `--watch` flag isn't being passed properly with your version of esbuild. If you want to use your version of esbuild, maybe try changing the watch script in `spectacular/package.json` to `node ./esbuild.js -- --watch`

Not sure if this will work, but worth a try

**Comment by charlwillia6** [comment]
This is happening to me too, without installing a different version of esbuild.  I am just running the commands that are stated in the CONTRIBUTING.md file.
