### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by shreeraj04** [meltylabs/melty#47]
I just took the latest pull where setup files are moved inside scripts. I am running melty_setup.sh and tried melty_install_deps.sh also. Getting similar output with error. By the way I am on Ubuntu.

```
$ node build/npm/preinstall.js
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "electron-builder > app-builder-lib@24.13.3" has unmet peer dependency "electron-builder-squirrel-windows@24.13.3".
warning " > tsec@0.2.7" has unmet peer dependency "@bazel/bazelisk@>=1.7.5".
warning " > tsec@0.2.7" has unmet peer dependency "@bazel/concatjs@>=5.3.0".
[4/4] Building fresh packages...
[1/21] ⢀ @parcel/watcher
[21/21] ⢀ windows-foreground-love
[18/21] ⢀ electron
[6/21] ⢀ @vscode/sqlite3
error /media/shreeraj/New Volume/GIT/melty/node_modules/@vscode/sqlite3: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /media/shreeraj/New Volume/GIT/melty/node_modules/@vscode/sqlite3
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@10.1.0
gyp info using node@20.17.0 | linux | x64
gyp info find Python using Python version 3.10.12 found at "/usr/bin/python3"

gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args 'binding.gyp',
gyp info spawn args '-f',
gyp info spawn args 'make',
gyp info spawn args '-I',
gyp info spawn args '/media/shreeraj/New Volume/GIT/melty/node_modules/@vscode/sqlite3/build/config.gypi',
gyp info spawn args '-I',
gyp info spawn args '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args '-I',
gyp info spawn args '/home/shreeraj/.cache/node-gyp/30.3.1/include/node/common.gypi',
gyp info spawn args '-Dlibrary=shared_library',
gyp info spawn args '-Dvisibility=default',
gyp info spawn args '-Dnode_root_dir=/home/shreeraj/.cache/node-gyp/30.3.1',
gyp info spawn args '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args '-Dnode_lib_file=/home/shreeraj/.cache/node-gyp/30.3.1/<(target_arch)/node.lib',
gyp info spawn args '-Dmodule_root_dir=/media/shreeraj/New Volume/GIT/melty/node_modules/@vscode/sqlite3',
gyp info spawn args '-Dnode_engine=v8',
gyp info spawn args '--depth=.',
gyp info spawn args '--no-parallel',
gyp info spawn args '--generator-output',
gyp info spawn args 'build',
gyp info spawn args '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/media/shreeraj/New Volume/GIT/melty/node_modules/@vscode/sqlite3/build'
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c
/bin/sh: 1: Volume/GIT/melty/node_modules/@vscode/sqlite3/build/Release/lib.host:/media/shreeraj/New: not found
mkdir: cannot create directory ‘/media/shreeraj/New’: Permission denied
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3390400/sqlite3.o
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c: In function ‘cellArea’:
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:200223:22: warning: this statement may fall through [-Wimplicit-fallthrough=]
200223 |       case 5:  area  = p->aCoord[9].f - p->aCoord[8].f;
       |                ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:200224:7: note: here
200224 |       case 4:  area *= p->aCoord[7].f - p->aCoord[6].f;
       |       ^~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:200224:21: warning: this statement may fall through [-Wimplicit-fallthrough=]
200224 |       case 4:  area *= p->aCoord[7].f - p->aCoord[6].f;
       |                ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:200225:7: note: here
200225 |       case 3:  area *= p->aCoord[5].f - p->aCoord[4].f;
       |       ^~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:200225:21: warning: this statement may fall through [-Wimplicit-fallthrough=]
200225 |       case 3:  area *= p->aCoord[5].f - p->aCoord[4].f;
       |                ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:200226:7: note: here
200226 |       case 2:  area *= p->aCoord[3].f - p->aCoord[2].f;
       |       ^~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:200226:21: warning: this statement may fall through [-Wimplicit-fallthrough=]
200226 |       case 2:  area *= p->aCoord[3].f - p->aCoord[2].f;
       |                ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:200227:7: note: here
200227 |       default: area *= p->aCoord[1].f - p->aCoord[0].f;
       |       ^~~~~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:200233:22: warning: this statement may fall through [-Wimplicit-fallthrough=]
200233 |       case 5:  area  = (i64)p->aCoord[9].i - (i64)p->aCoord[8].i;
       |                ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:200234:7: note: here
200234 |       case 4:  area *= (i64)p->aCoord[7].i - (i64)p->aCoord[6].i;
       |       ^~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:200234:21: warning: this statement may fall through [-Wimplicit-fallthrough=]
200234 |       case 4:  area *= (i64)p->aCoord[7].i - (i64)p->aCoord[6].i;
       |                ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:200235:7: note: here
200235 |       case 3:  area *= (i64)p->aCoord[5].i - (i64)p->aCoord[4].i;
       |       ^~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:200235:21: warning: this statement may fall through [-Wimplicit-fallthrough=]
200235 |       case 3:  area *= (i64)p->aCoord[5].i - (i64)p->aCoord[4].i;
       |                ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:200236:7: note: here
200236 |       case 2:  area *= (i64)p->aCoord[3].i - (i64)p->aCoord[2].i;
       |       ^~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:200236:21: warning: this statement may fall through [-Wimplicit-fallthrough=]
200236 |       case 2:  area *= (i64)p->aCoord[3].i - (i64)p->aCoord[2].i;
       |                ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:200237:7: note: here
200237 |       default: area *= (i64)p->aCoord[1].i - (i64)p->aCoord[0].i;
       |       ^~~~~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c: In function ‘rtreeCallbackConstraint’:
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:199362:56: warning: this statement may fall through [-Wimplicit-fallthrough=]
199362 |                 readCoord(pCellData+32, &c); aCoord[8] = c.f;
       |                                              ~~~~~~~~~~^~~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:199363:7: note: here
199363 |       case 8:   readCoord(pCellData+28, &c); aCoord[7] = c.f;
       |       ^~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:199364:56: warning: this statement may fall through [-Wimplicit-fallthrough=]
199364 |                 readCoord(pCellData+24, &c); aCoord[6] = c.f;
       |                                              ~~~~~~~~~~^~~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:199365:7: note: here
199365 |       case 6:   readCoord(pCellData+20, &c); aCoord[5] = c.f;
       |       ^~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:199366:56: warning: this statement may fall through [-Wimplicit-fallthrough=]
199366 |                 readCoord(pCellData+16, &c); aCoord[4] = c.f;
       |                                              ~~~~~~~~~~^~~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:199367:7: note: here
199367 |       case 4:   readCoord(pCellData+12, &c); aCoord[3] = c.f;
       |       ^~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:199368:56: warning: this statement may fall through [-Wimplicit-fallthrough=]
199368 |                 readCoord(pCellData+8,  &c); aCoord[2] = c.f;
       |                                              ~~~~~~~~~~^~~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:199369:7: note: here
199369 |       default:  readCoord(pCellData+4,  &c); aCoord[1] = c.f;
       |       ^~~~~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:199377:56: warning: this statement may fall through [-Wimplicit-fallthrough=]
199377 |                 readCoord(pCellData+32, &c); aCoord[8] = c.i;
       |                                              ~~~~~~~~~~^~~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:199378:7: note: here
199378 |       case 8:   readCoord(pCellData+28, &c); aCoord[7] = c.i;
       |       ^~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:199379:56: warning: this statement may fall through [-Wimplicit-fallthrough=]
199379 |                 readCoord(pCellData+24, &c); aCoord[6] = c.i;
       |                                              ~~~~~~~~~~^~~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:199380:7: note: here
199380 |       case 6:   readCoord(pCellData+20, &c); aCoord[5] = c.i;
       |       ^~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:199381:56: warning: this statement may fall through [-Wimplicit-fallthrough=]
199381 |                 readCoord(pCellData+16, &c); aCoord[4] = c.i;
       |                                              ~~~~~~~~~~^~~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:199382:7: note: here
199382 |       case 4:   readCoord(pCellData+12, &c); aCoord[3] = c.i;
       |       ^~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:199383:56: warning: this statement may fall through [-Wimplicit-fallthrough=]
199383 |                 readCoord(pCellData+8,  &c); aCoord[2] = c.i;
       |                                              ~~~~~~~~~~^~~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:199384:7: note: here
199384 |       default:  readCoord(pCellData+4,  &c); aCoord[1] = c.i;
       |       ^~~~~~~
rm -f Release/obj.target/deps/sqlite3.a Release/obj.target/deps/sqlite3.a.ar-file-list; mkdir -p `dirname Release/obj.target/deps/sqlite3.a`
ar crs Release/obj.target/deps/sqlite3.a @Release/obj.target/deps/sqlite3.a.ar-file-list
  COPY Release/sqlite3.a
  CC(target) Release/obj.target/nothing/node_modules/node-addon-api/nothing.o
rm -f Release/obj.target/node_modules/node-addon-api/nothing.a Release/obj.target/node_modules/node-addon-api/nothing.a.ar-file-list; mkdir -p `dirname Release/obj.target/node_modules/node-addon-api/nothing.a`
ar crs Release/obj.target/node_modules/node-addon-api/nothing.a @Release/obj.target/node_modules/node-addon-api/nothing.a.ar-file-list
  COPY Release/nothing.a
  CXX(target) Release/obj.target/vscode-sqlite3/src/backup.o
../src/backup.cc:2:10: fatal error: napi.h: No such file or directory
    2 | #include <napi.h>
      |          ^~~~~~~~
compilation terminated.
make: *** [vscode-sqlite3.target.mk:149: Release/obj.target/vscode-sqlite3/src/backup.o] Error 1
make: Leaving directory '/media/shreeraj/New Volume/GIT/melty/node_modules/@vscode/sqlite3/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:209:23)
gyp ERR! System Linux 6.5.0-1027-oem
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /media/shreeraj/New Volume/GIT/melty/node_modules/@vscode/sqlite3





up to date, audited 371 packages in 1s

78 packages are looking for funding
  run `npm fund` for details

3 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

added 16 packages, removed 1200 packages, changed 39 packages, and audited 533 packages in 3s

133 packages are looking for funding
  run `npm fund` for details

4 vulnerabilities (2 moderate, 2 high)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.

> melty@0.28.0 compile
> node ./esbuild.js

node:internal/streams/writable:480
      throw new ERR_INVALID_ARG_TYPE(
            ^

TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at _write (node:internal/streams/writable:480:13)
    at Writable.write (node:internal/streams/writable:508:10)
    at /media/shreeraj/New Volume/GIT/melty/extensions/spectacular/esbuild.js:83:18
    at Object.<anonymous> (/media/shreeraj/New Volume/GIT/melty/extensions/spectacular/esbuild.js:86:3)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v20.17.0
./scripts/melty_setup.sh: line 16: cd: ../supermaven: No such file or directory

```

Also does it work out in VS code extension? I can see it uses Anthropic API key. With this installation do we need to have the key as well ?

**Comment by mrtkrcm** [comment]
You may just need to use Yarn 1.x

```sh
corepack use yarn@1
```

**Comment by shreeraj04** [comment]
I did @mrtkrcm but still getting similar error.

```
Installing yarn@1.22.22 in the project...

yarn install v1.22.22
$ node build/npm/preinstall.js
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "electron-builder > app-builder-lib@24.13.3" has unmet peer dependency "electron-builder-squirrel-windows@24.13.3".
warning " > tsec@0.2.7" has unmet peer dependency "@bazel/bazelisk@>=1.7.5".
warning " > tsec@0.2.7" has unmet peer dependency "@bazel/concatjs@>=5.3.0".
[4/4] Building fresh packages...
[1/21] ⠠ @parcel/watcher
[21/21] ⠠ windows-foreground-love
[18/21] ⠠ electron
[6/21] ⠠ @vscode/sqlite3
error /media/shreeraj/New Volume/GIT/melty/node_modules/@vscode/sqlite3: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /media/shreeraj/New Volume/GIT/melty/node_modules/@vscode/sqlite3
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@10.1.0
gyp info using node@20.17.0 | linux | x64
gyp info find Python using Python version 3.10.12 found at "/usr/bin/python3"

gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args 'binding.gyp',
gyp info spawn args '-f',
gyp info spawn args 'make',
gyp info spawn args '-I',
gyp info spawn args '/media/shreeraj/New Volume/GIT/melty/node_modules/@vscode/sqlite3/build/config.gypi',
gyp info spawn args '-I',
gyp info spawn args '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args '-I',
gyp info spawn args '/home/shreeraj/.cache/node-gyp/30.3.1/include/node/common.gypi',
gyp info spawn args '-Dlibrary=shared_library',
gyp info spawn args '-Dvisibility=default',
gyp info spawn args '-Dnode_root_dir=/home/shreeraj/.cache/node-gyp/30.3.1',
gyp info spawn args '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args '-Dnode_lib_file=/home/shreeraj/.cache/node-gyp/30.3.1/<(target_arch)/node.lib',
gyp info spawn args '-Dmodule_root_dir=/media/shreeraj/New Volume/GIT/melty/node_modules/@vscode/sqlite3',
gyp info spawn args '-Dnode_engine=v8',
gyp info spawn args '--depth=.',
gyp info spawn args '--no-parallel',
gyp info spawn args '--generator-output',
gyp info spawn args 'build',
gyp info spawn args '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/media/shreeraj/New Volume/GIT/melty/node_modules/@vscode/sqlite3/build'
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c
/bin/sh: 1: Volume/GIT/melty/node_modules/@vscode/sqlite3/build/Release/lib.host:/media/shreeraj/New: not found
mkdir: cannot create directory ‘/media/shreeraj/New’: Permission denied
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3390400/sqlite3.o
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c: In function ‘cellArea’:
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:200223:22: warning: this statement may fall through [-Wimplicit-fallthrough=]
200223 |       case 5:  area  = p->aCoord[9].f - p->aCoord[8].f;
       |                ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:200224:7: note: here
200224 |       case 4:  area *= p->aCoord[7].f - p->aCoord[6].f;
       |       ^~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:200224:21: warning: this statement may fall through [-Wimplicit-fallthrough=]
200224 |       case 4:  area *= p->aCoord[7].f - p->aCoord[6].f;
       |                ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:200225:7: note: here
200225 |       case 3:  area *= p->aCoord[5].f - p->aCoord[4].f;
       |       ^~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:200225:21: warning: this statement may fall through [-Wimplicit-fallthrough=]
200225 |       case 3:  area *= p->aCoord[5].f - p->aCoord[4].f;
       |                ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:200226:7: note: here
200226 |       case 2:  area *= p->aCoord[3].f - p->aCoord[2].f;
       |       ^~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:200226:21: warning: this statement may fall through [-Wimplicit-fallthrough=]
200226 |       case 2:  area *= p->aCoord[3].f - p->aCoord[2].f;
       |                ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:200227:7: note: here
200227 |       default: area *= p->aCoord[1].f - p->aCoord[0].f;
       |       ^~~~~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:200233:22: warning: this statement may fall through [-Wimplicit-fallthrough=]
200233 |       case 5:  area  = (i64)p->aCoord[9].i - (i64)p->aCoord[8].i;
       |                ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:200234:7: note: here
200234 |       case 4:  area *= (i64)p->aCoord[7].i - (i64)p->aCoord[6].i;
       |       ^~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:200234:21: warning: this statement may fall through [-Wimplicit-fallthrough=]
200234 |       case 4:  area *= (i64)p->aCoord[7].i - (i64)p->aCoord[6].i;
       |                ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:200235:7: note: here
200235 |       case 3:  area *= (i64)p->aCoord[5].i - (i64)p->aCoord[4].i;
       |       ^~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:200235:21: warning: this statement may fall through [-Wimplicit-fallthrough=]
200235 |       case 3:  area *= (i64)p->aCoord[5].i - (i64)p->aCoord[4].i;
       |                ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:200236:7: note: here
200236 |       case 2:  area *= (i64)p->aCoord[3].i - (i64)p->aCoord[2].i;
       |       ^~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:200236:21: warning: this statement may fall through [-Wimplicit-fallthrough=]
200236 |       case 2:  area *= (i64)p->aCoord[3].i - (i64)p->aCoord[2].i;
       |                ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:200237:7: note: here
200237 |       default: area *= (i64)p->aCoord[1].i - (i64)p->aCoord[0].i;
       |       ^~~~~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c: In function ‘rtreeCallbackConstraint’:
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:199362:56: warning: this statement may fall through [-Wimplicit-fallthrough=]
199362 |                 readCoord(pCellData+32, &c); aCoord[8] = c.f;
       |                                              ~~~~~~~~~~^~~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:199363:7: note: here
199363 |       case 8:   readCoord(pCellData+28, &c); aCoord[7] = c.f;
       |       ^~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:199364:56: warning: this statement may fall through [-Wimplicit-fallthrough=]
199364 |                 readCoord(pCellData+24, &c); aCoord[6] = c.f;
       |                                              ~~~~~~~~~~^~~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:199365:7: note: here
199365 |       case 6:   readCoord(pCellData+20, &c); aCoord[5] = c.f;
       |       ^~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:199366:56: warning: this statement may fall through [-Wimplicit-fallthrough=]
199366 |                 readCoord(pCellData+16, &c); aCoord[4] = c.f;
       |                                              ~~~~~~~~~~^~~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:199367:7: note: here
199367 |       case 4:   readCoord(pCellData+12, &c); aCoord[3] = c.f;
       |       ^~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:199368:56: warning: this statement may fall through [-Wimplicit-fallthrough=]
199368 |                 readCoord(pCellData+8,  &c); aCoord[2] = c.f;
       |                                              ~~~~~~~~~~^~~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:199369:7: note: here
199369 |       default:  readCoord(pCellData+4,  &c); aCoord[1] = c.f;
       |       ^~~~~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:199377:56: warning: this statement may fall through [-Wimplicit-fallthrough=]
199377 |                 readCoord(pCellData+32, &c); aCoord[8] = c.i;
       |                                              ~~~~~~~~~~^~~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:199378:7: note: here
199378 |       case 8:   readCoord(pCellData+28, &c); aCoord[7] = c.i;
       |       ^~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:199379:56: warning: this statement may fall through [-Wimplicit-fallthrough=]
199379 |                 readCoord(pCellData+24, &c); aCoord[6] = c.i;
       |                                              ~~~~~~~~~~^~~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:199380:7: note: here
199380 |       case 6:   readCoord(pCellData+20, &c); aCoord[5] = c.i;
       |       ^~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:199381:56: warning: this statement may fall through [-Wimplicit-fallthrough=]
199381 |                 readCoord(pCellData+16, &c); aCoord[4] = c.i;
       |                                              ~~~~~~~~~~^~~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:199382:7: note: here
199382 |       case 4:   readCoord(pCellData+12, &c); aCoord[3] = c.i;
       |       ^~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:199383:56: warning: this statement may fall through [-Wimplicit-fallthrough=]
199383 |                 readCoord(pCellData+8,  &c); aCoord[2] = c.i;
       |                                              ~~~~~~~~~~^~~~~
Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c:199384:7: note: here
199384 |       default:  readCoord(pCellData+4,  &c); aCoord[1] = c.i;
       |       ^~~~~~~
rm -f Release/obj.target/deps/sqlite3.a Release/obj.target/deps/sqlite3.a.ar-file-list; mkdir -p `dirname Release/obj.target/deps/sqlite3.a`
ar crs Release/obj.target/deps/sqlite3.a @Release/obj.target/deps/sqlite3.a.ar-file-list
  COPY Release/sqlite3.a
  CC(target) Release/obj.target/nothing/node_modules/node-addon-api/nothing.o
rm -f Release/obj.target/node_modules/node-addon-api/nothing.a Release/obj.target/node_modules/node-addon-api/nothing.a.ar-file-list; mkdir -p `dirname Release/obj.target/node_modules/node-addon-api/nothing.a`
ar crs Release/obj.target/node_modules/node-addon-api/nothing.a @Release/obj.target/node_modules/node-addon-api/nothing.a.ar-file-list
  COPY Release/nothing.a
  CXX(target) Release/obj.target/vscode-sqlite3/src/backup.o
../src/backup.cc:2:10: fatal error: napi.h: No such file or directory
    2 | #include <napi.h>
      |          ^~~~~~~~
compilation terminated.
make: *** [vscode-sqlite3.target.mk:149: Release/obj.target/vscode-sqlite3/src/backup.o] Error 1
make: Leaving directory '/media/shreeraj/New Volume/GIT/melty/node_modules/@vscode/sqlite3/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:209:23)
gyp ERR! System Linux 6.5.0-1027-oem
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /media/shreeraj/New Volume/GIT/melty/node_modules/@vscode/sqlite3
```

**Comment by mrtkrcm** [comment]
its either due to having a space in your folder name `New Volume` or your `node-gyp` version. try in a folder without space or add `node-gyp` as dependency so it would build native deps based on your system `yarn add node-gyp`

**Comment by abhi12299** [comment]
Correct. The error is right here in the logs:
```
ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3390400/sqlite3.c
/bin/sh: 1: Volume/GIT/melty/node_modules/@vscode/sqlite3/build/Release/lib.host:/media/shreeraj/New: not found
mkdir: cannot create directory ‘/media/shreeraj/New’: Permission denied
```
