### ISSUE TITLE
Git extension issue?

### ISSUE THREAD

**Issue by abhi12299** [meltylabs/melty#8]
### Issue
When working with melty, the git extension is unable to execute commands. 

### Reproduction steps:
- Create a new melty workspace with git repository.
- Prompt melty to create a file: `Create a nodejs script to print hello world to console`
- Once done, ask it to make any changes to the file: `modify the script to output hello world 10 times`
- When the `Committing user changes` text shows up on the UI, notice the logs and you'll see it failing.

I tried copying the latest git extension from https://github.com/microsoft/vscode/tree/main/extensions/git but it is also not working (there were typescript issues with the extension and even after adding `ts-nocheck`, it still fails because some internal function definitions required by the extension are missing)

### Logs:
```
[82726:0905/163411.940397:INFO:CONSOLE(269)] "%c  ERR color: #f33 [Extension Host] Error comitting changeset Error: Failed to execute git
        at Git._exec (/Users/abhi/Desktop/Work/projects/melty/extensions/git/out/git.js:460:35)
        at async Git.exec (/Users/abhi/Desktop/Work/projects/melty/extensions/git/out/git.js:407:16)
        at async Repository.exec (/Users/abhi/Desktop/Work/projects/melty/extensions/git/out/git.js:790:16)
        at async Repository.handleCommitError (/Users/abhi/Desktop/Work/projects/melty/extensions/git/out/git.js:1299:13)
        at async Repository.commit (/Users/abhi/Desktop/Work/projects/melty/extensions/git/out/git.js:1274:13)
        at async /Users/abhi/Desktop/Work/projects/melty/extensions/git/out/repository.js:981:17
        at async Repository.retryRun (/Users/abhi/Desktop/Work/projects/melty/extensions/git/out/repository.js:1667:24)
        at async Repository.run (/Users/abhi/Desktop/Work/projects/melty/extensions/git/out/repository.js:1641:28)
        at async Repository.commit (/Users/abhi/Desktop/Work/projects/melty/extensions/git/out/repository.js:971:13)
        at async GitManager.commitChangeSet (/Users/abhi/Desktop/Work/projects/melty/extensions/spectacular/out/services/GitManager.js:172:13)
        at async Coder.applyChangesToGetNextJoule (/Users/abhi/Desktop/Work/projects/melty/extensions/spectacular/out/backend/assistants/coder.js:137:26)
        at async Coder.claudeOutputToConversation (/Users/abhi/Desktop/Work/projects/melty/extensions/spectacular/out/backend/assistants/coder.js:118:27)
        at async Coder.respond (/Users/abhi/Desktop/Work/projects/melty/extensions/spectacular/out/backend/assistants/coder.js:107:16)
        at async Task.respondBot (/Users/abhi/Desktop/Work/projects/melty/extensions/spectacular/out/backend/tasks.js:116:33)
        at async /Users/abhi/Desktop/Work/projects/melty/extensions/spectacular/out/backend/tasks.js:197:13", source: vscode-file://vscode-app/Users/abhi/Desktop/Work/projects/melty/out/vs/platform/log/common/log.js (269)
[82726:0905/163411.940576:INFO:CONSOLE(104)] "%c[Extension Host] %cError comitting changeset color: blue color:  Error: Failed to execute git
        at Git._exec (/Users/abhi/Desktop/Work/projects/melty/extensions/git/out/git.js:460:35)
        at async Git.exec (/Users/abhi/Desktop/Work/projects/melty/extensions/git/out/git.js:407:16)
        at async Repository.exec (/Users/abhi/Desktop/Work/projects/melty/extensions/git/out/git.js:790:16)
        at async Repository.handleCommitError (/Users/abhi/Desktop/Work/projects/melty/extensions/git/out/git.js:1299:13)
        at async Repository.commit (/Users/abhi/Desktop/Work/projects/melty/extensions/git/out/git.js:1274:13)
        at async /Users/abhi/Desktop/Work/projects/melty/extensions/git/out/repository.js:981:17
        at async Repository.retryRun (/Users/abhi/Desktop/Work/projects/melty/extensions/git/out/repository.js:1667:24)
        at async Repository.run (/Users/abhi/Desktop/Work/projects/melty/extensions/git/out/repository.js:1641:28)
        at async Repository.commit (/Users/abhi/Desktop/Work/projects/melty/extensions/git/out/repository.js:971:13)
        at async GitManager.commitChangeSet (/Users/abhi/Desktop/Work/projects/melty/extensions/spectacular/out/services/GitManager.js:172:13)
        at async Coder.applyChangesToGetNextJoule (/Users/abhi/Desktop/Work/projects/melty/extensions/spectacular/out/backend/assistants/coder.js:137:26)
        at async Coder.claudeOutputToConversation (/Users/abhi/Desktop/Work/projects/melty/extensions/spectacular/out/backend/assistants/coder.js:118:27)
        at async Coder.respond (/Users/abhi/Desktop/Work/projects/melty/extensions/spectacular/out/backend/assistants/coder.js:107:16)
        at async Task.respondBot (/Users/abhi/Desktop/Work/projects/melty/extensions/spectacular/out/backend/tasks.js:116:33)
        at async /Users/abhi/Desktop/Work/projects/melty/extensions/spectacular/out/backend/tasks.js:197:13 (at console.<anonymous> (/Users/abhi/Desktop/Work/projects/melty/out/vs/workbench/api/common/extHostConsoleForwarder.js:45:26))", source: vscode-file://vscode-app/Users/abhi/Desktop/Work/projects/melty/out/vs/base/common/console.js (104)
```

**Comment by jacksondc** [comment]
Thanks Abhi. Maybe try running the `Show Git Output` command (cmd+shift+P) and see if there are any errors there?

**Comment by abhi12299** [comment]
Sure, will report back. Also, a side note: the development setup is a bit confusing right now. I raised a PR earlier, which I had to close because I went on a tangent trying to set up melty. I'm working on improving the DX and write some simple documentation for local setup. Will raise a PR soon, with the correct setup hopefully 🤞

**Comment by abhi12299** [comment]
Also, if there's a feature list to work on, or a roadmap for the upcoming features, it would be easier for potential contributors to pick and work on them.
